CREATE TABLE DATASOURCECONFIG (
	id IDENTITY PRIMARY KEY,
	driverclassname VARCHAR(255),
	url VARCHAR(255),
	name VARCHAR(255),
	username VARCHAR(255),
	password VARCHAR(255),
  tenantid INT(11),
	initialize BOOLEAN
);

CREATE TABLE PRODUCT (
	id IDENTITY PRIMARY KEY,
	name VARCHAR(255)
);

CREATE TABLE USUARIO (
	id IDENTITY PRIMARY KEY,
	email VARCHAR(255),
	senha VARCHAR(200),
	perfil CHAR(1)
);